spring:
    application:
        name: ameri
    datasource:
        url: jdbc:postgresql://localhost:5432/ameri
        username: postgres 
        password: 2007
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
    level:
         com:
             winnerx0:
                 - INFO
                 - DEBUG
                 - ERROR
                 - FATAL
                 - WARN
                 - TRACE
jwt:
    secretKey: qks12vBcAuV1GyI3tFcEFdQZwPIxOb3Loxjc0wo0tv0=

cloudinary:
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

gemini:
    api-key: ${GEMINI_API_KEY}

email:
    sender:
        host: smtp.gmail.com
        debug: true
        user: ${GMAIL_USER}
        password: ${GMAIL_PASSWORD}


